#详细说明见文件尾部
[FileInfo]
  FileName="oeminfo_tsinghuatongfangcomputer_e500__2200980001776100571.toml"
  VendorInfo="fttf"
  Version="0.0.1"
  Data="2022-12-01"

[Computer.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  HOME_URL="replace value"  
  OsDescription="replace value"  
  Type="replace value"  
  OS="replace value"  


[CPU.VendorLabel]
  Name="Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz"
  Vendor="Intel(R) Corporation"
  CPU ID="replace value"  
  CPU implementer="replace value"  
  CPU architecture="replace value"  
  CPU variant="replace value"  
  CPU part="replace value"  
  CPU revision="replace value"  
  Core ID="replace value"  
  Threads="replace value"  
  Current Speed="replace value"  
  Max Speed="replace value"  
  BogoMIPS="replace value"  
  Architecture="replace value"  
  CPU Family="replace value"  
  Model="replace value"  
  Virtualization="replace value"  
  Flags="replace value"  
  Extensions="replace value"  
  L3 Cache="replace value"  
  L2 Cache="replace value"  
  L1i Cache="replace value"  
  L1d Cache="replace value"  
  Stepping="replace value"  
  Frequency="replace value"  

[Motherboard.BIOSInformation]
  Name="BIOS Information"                      # 注意：该条Name 的值不更改 对应命令dmidecode -t 0
  Vendor="replace value"  
  Version="replace value"  
  Release Date="replace value"  
  Address="replace value"  
  Runtime Size="replace value"  
  ROM Size="replace value"  
  Characteristics="replace value"  
  BIOS Revision="replace value" 
 
  Firmware Revision="replace value"  
  Chipset="replace value"  
  Asset Tag="replace value"  
  Location In Chassis="replace value"  
  Chassis Handle="replace value"  
  SMBIOS Version="replace value"  
  Serial Number="replace value"  
  Product Name="replace value"  

[Motherboard.BaseBoardInformation]
  Name="Base Board Information"          # 注意：该条Name 的值不更改 对应命令 dmidecode -t 2            
  Vendor="replace value"  
  Manufacturer="replace value"  
  Product Name="replace value"
  Version="replace value"  
  Serial Number="replace value" 
  Asset Tag="replace value" 
  Features="replace value" 
  Location In Chassis="replace value"  
  Chassis Handle="replace value" 
  Type="replace value"  
  Contained Object Handles="replace value"  

  Chipset="replace value"    
  SMBIOS Version="replace value"  
   

[Motherboard.ChassisInformation]
  Name="Chassis Information"                     # 注意：该条Name 的值不更改 对应命令 dmidecode -t 3
  Manufacturer="replace value"  
  Type="replace value"  
  Lock="replace value"  
  Version="replace value"  
  Serial Number="replace value"  
  Asset Tag="replace value"  
  Boot-up State="replace value"  
  Power Supply State="replace value"  
  Thermal State="replace value"  
  Security Status="replace value"  
  OEM Information="replace value"  
  Height="replace value"  
  Number Of Power Cords="replace value"  
  Contained Elements="replace value"  
  SKU Number="replace value"  


  Chipset="replace value"  
  Location In Chassis="replace value"  
  Chassis Handle="replace value"  
  SMBIOS Version="replace value"  
  Product Name="replace value"  

[Motherboard.PhysicalMemoryArray]
  Name="Physical Memory Array"                       # 注意：该条Name 的值不更改 对应命令  dmidecode -t 17
  Array Handle="replace value"  
  Error Information Handle="replace value"  
  Total Width="replace value"  
  Data Width="replace value"  
  Size="replace value"  
  Form Factor="replace value"  
  Set="replace value"  
  Locator="replace value"  
  Bank Locator="replace value"  
  Type="replace value"  
  Type Detail="replace value"  
  Speed="replace value"  
  Manufacturer="replace value"  
  Serial Number="replace value"
  Asset Tag="replace value"  

  Part Number="replace value"  
  Rank="replace value"  

  Configured Memory Speed="replace value" 
 
  Minimum Voltage="replace value"  
  Maximum Voltage="replace value"  
  Configured Voltage="replace value"  

  Memory Technology="replace value"  
  Memory Operating Mode Capability="replace value"  
  Firmware Version="replace value"  
  Module Manufacturer ID="replace value" 

  Number Of Devices="replace value"  
  Location="replace value"  
  Maximum Capacity="replace value"  
  Chipset="replace value"  

  Location In Chassis="replace value"  
  Chassis Handle="replace value"  
  SMBIOS Version="replace value"    
  Product Name="replace value"  
  Type="replace value"  


[Motherboard.SystemInformation]
  Name="System Information"                     # 注意：该条Name 的值不更改 对应命令  dmidecode -t 1
  Vendor="replace value"  
  Asset Tag="replace value"  
  Location In Chassis="replace value"  
  Chassis Handle="replace value"  
  SMBIOS Version="replace value"  
  Serial Number="replace value"  
  Product Name="replace value"  

  Manufacturer="replace value"  
  Version="replace value"  
  UUID="replace value"  
  Wake-up Type="replace value"  
  SKU Number="replace value"  
  Family="replace value"  
  Chipset="replace value"  

  Release Date="replace value"  
  Address="replace value"  
  Runtime Size="replace value"  
  ROM Size="replace value"  
  Characteristics="replace value"  
  BIOS Revision="replace value"  
  Firmware Revision="replace value"  
   Asset Tag="replace value"  
  Features="replace value"  
  Type="replace value"  
  Contained Object Handles="replace value"  
  UUID="replace value"  
  Wake-up Type="replace value"  
  SKU Number="replace value"  
  Family="replace value"  
  Type="replace value"  
  Lock="replace value"  
  Serial Number="replace value"  
   Asset Tag="replace value"  
  Boot-up State="replace value"  
  Power Supply State="replace value"  
  Thermal State="replace value"  
  Security Status="replace value"  
  OEM Information="replace value"  
  Height="replace value"  
  Number Of Power Cords="replace value"  
  Contained Elements="replace value"  
  SKU Number="replace value"  
  Error Correction Type="replace value"  
  Error Information Handle="replace value"  
  BIOS ROMSIZE="replace value"  
  Release date="replace value"  
  Board   Name="replace value"  
  Family="replace value"  
  BIOS Information="replace value"  
  Base Board Information="replace value"  
  System Information="replace value"  
  Chassis Information="replace value"  
  Physical Memory Array="replace value"  
  Language Description Format="replace value"  
  Installable Languages="replace value"  
  Currently Installed Language="replace value"  


[Memory.VendorLabel]
  Vendor="replace value"
  Name="replace value"
  Array Handle="replace value"  
  Error Information Handle="replace value"  
  Form Factor="replace value"  
  Set="replace value"  
  Bank Locator="replace value"  
  Type Detail="replace value"  
   Asset Tag="replace value"  
  Part Number="replace value"  
  Rank="replace value"  
  Memory Technology="replace value"  
  Memory Operating Mode Capability="replace value"  
  Firmware Version="replace value"  
  Module Manufacturer ID="replace value"  
  Module Product ID="replace value"  
  Memory Subsystem Controller Manufacturer ID="replace value"  
  Memory Subsystem Controller Product ID="replace value"  
  Non-Volatile Size="replace value"  
  Volatile Size="replace value"  
  Cache Size="replace value"  
  Logical Size="replace value"  
  Size="replace value"  
  Type="replace value"  
  Speed="replace value"  
  Total Width="replace value"  
  Locator="replace value"  
  Serial Number="replace value"  
  Configured Voltage="replace value"  
  Maximum Voltage="replace value"  
  Minimum Voltage="replace value"  
  Configured Speed="replace value"  
  Data Width="replace value"  

[Storage.VendorLabel]
  Vendor="replace value"
  Name="replace value"
  Hardware Class="replace value"  
  Device File="replace value"  
  ansiVersion="replace value"  
  bus info="replace value"  
  logical name="replace value"  
  logicalsectorsize="replace value"  
  physical id="replace value"  
  sectorsize="replace value"  
  guid="replace value"  
  Config Status="replace value"  
  Device Number="replace value"  
  Geometry (Logical)="replace value"  
  Model="replace value"  
  Media Type="replace value"  
  Size="replace value"  
  Capabilities="replace value"  
  Firmware Version="replace value"  
  Speed="replace value"  
  Serial Number="replace value"  
  Interface="replace value"  
  Rotation Rate="replace value"  


[Storage.2.VendorLabel]
  Vendor="WDC"
  Name="WDC WD10EZEX-08WN4A0"
  Hardware Class="replace value"  
  Device File="replace value"  
  ansiVersion="replace value"  
  bus info="replace value"  
  logical name="replace value"  

[DisplayGPU.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Modalias="pci:v00001002d00006611sv00001642sd00001997b"
  Vendor_ID="1002"
  Product_ID="8811"
  Model="replace value"  
  Graphics Memory="replace value"  
  width="replace value"  
  clock="replace value"  
  irq="replace value"  
  capabilities="replace value"  
  bus info="replace value"  
  ioport="replace value"  
  memory="replace value"  
  Memory Address="replace value"  
  IO Port="replace value"  
  Bus Info="replace value"  
  Maximum Resolution="replace value"  
  Minimum Resolution="replace value"  
  Current Resolution="replace value"  
  Driver="replace value"  
  Description="replace value"  
  Clock="replace value"  
  DP="replace value"  
  eDP="replace value"  
  HDMI="replace value"  
  VGA="replace value"  
  DVI="replace value"  
  DigitalOutput="replace value"  
  Display Output="replace value"  
  Capabilities="replace value"  
  IRQ="replace value"  
  Device  ="replace value"
  SubVendor  ="replace value"
  SubDevice  ="replace value"
  Driver Modules  ="replace value"
  Config Status  ="replace value"
  latency  ="replace value"
  GDDR capacity  ="replace value"
  GPU vendor  ="replace value"
  GPU type  ="replace value"
  EGL version  ="replace value"
  EGL client APIs  ="replace value"
  GL version  ="replace value"
  GLSL version  ="replace value"

[Monitor.VendorLabel]
  Vendor="VIEWSONIC"
  Name="VIEWSONIC VA2430-H-3"
  Date="replace value"  
  Type="replace value"  
  Display Input="replace value"  
  Interface Type="replace value"  
  Support Resolution="replace value"  
   Current Resolution="replace value"  
  Display Ratio="replace value"  
  Primary Monitor="replace value"  
  Size="replace value"  
  Serial Number="replace value"  
  Product Date="replace value"  

[NetWork.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Modalias="pci:v00008086d0000A3F0sv00001849sd0000288Ab
  ioport="replace value"  
  physical id="replace value"  
  network="replace value"  
  Type="replace value"  
  Bus Info="replace value"  
  Capabilities="replace value"  
  Driver Version="replace value"  
  Maximum Rate="replace value"  
  Negotiation Rate="replace value"  
  Port="replace value"  
  Multicast="replace value"  
  Link="replace value"  
  Latency="replace value"  
  IP="replace value"  
  Firmware="replace value"  
  Duplex="replace value"  
  Broadcast="replace value"  
  Auto Negotiation="replace value"  
  Memory Address="replace value"  
  IRQ="replace value"  
  MAC Address="replace value"  
  logical name="replace value"  

[SoundAudio.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Modalias="pci:v00008086d0000A3F0sv00001849sd0000288Ab"
  Device Name="replace value"  
  SubVendor="replace value"  
  SubDevice="replace value"  
  Driver Status="replace value"  
  Driver Activation Cmd="replace value"  
  Config Status="replace value"  
  latency="replace value"  
  Phys="replace value"  
  Sysfs="replace value"  
  Handlers="replace value"  
  PROP="replace value"  
  EV="replace value"  
  KEY="replace value"  
  Bus="replace value"  
Version="replace value"  
  Driver="replace value"  
  SysFS_Path="replace value"  
  Chip="replace value"  
  Capabilities="replace value"  
  Memory Address="replace value"  
  IRQ="replace value"  

[Bluetooth.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Modalias="usb:v8087p0AAAd0002dcE0dsc01dp01icE0isc"
  Bus="replace value"  
  BD Address="replace value"  
  ACL MTU="replace value"  
  SCO MTU="replace value"  
  Features="replace value"  
  Packet type="replace value"  
  Link policy="replace value"  
  Link mode="replace value"  
  Class="replace value"  
  Service Classes="replace value"  
  Device Class="replace value"  
  HCI   Version="replace value"  
  LMP   Version="replace value"  
  Sub  Version="replace value"  

  Device="replace value"  
  Serial ID="replace value"  
  product="replace value"  
  Class="replace value"  
  Powered="replace value"  
  Discoverable="replace value"  
  Pairable="replace value"  
  UUID="replace value"  
  Discovering="replace value"  
  Model="replace value"  
  Speed="replace value"  
  Maximum Power="replace value"  
  Driver Version="replace value"  
  Capabilities="replace value"  
  Bus Info="replace value"  
  logical name="replace value"  
  MAC Address="replace value"  

[Power.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  native-path="replace value"  
  power supply="replace value"  
  updated="replace value"  
  has history="replace value"  
  has statistics="replace value"  
  rechargeable="replace value"  
  state="replace value"  
  warning-level="replace value"  
  energy="replace value"  
  energy-empty="replace value"  
  energy-full="replace value"  
  energy-full-design="replace value"  
  energy-rate="replace value"  
  voltage="replace value"  
  percentage="replace value"  
  technology="replace value"  
  icon-Name="replace value"  
  online="replace value"  
  daemon-  Version="replace value"  
  on-battery="replace value"  
  lid-is-closed="replace value"  
  lid-is-present="replace value"  
  critical-action="replace value"  
  Model="replace value"  
  Serial Number="replace value"  
  Type="replace value"  
  Status="replace value"  
  Capacity="replace value"  
  Voltage="replace value"  
  Slot="replace value"  
  Design Capacity="replace value"  
  Design Voltage="replace value"  
  SBDS Version="replace value"  
  SBDS Serial Number="replace value"  
  SBDS Manufacture Date="replace value"  
  SBDS Chemistry="replace value"  
  Temperature="replace value"  

[Keyboard.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Modalias="usb:v1A2Cp2D23d0110dc00dsc00dp00ic03isc"
  Uniq="replace value"  
  PROP="replace value"  
  EV="replace value"  
  KEY="replace value"  
  MSC="replace value"  
  Device File="replace value"  
  Hardware Class="replace value"  
  physical id="replace value"  
  Model="replace value"  
  Interface="replace value"  
  Bus Info="replace value"  
  Speed="replace value"  
  Maximum Current="replace value"  
  Capabilities="replace value"  
  Revision="replace value"  
  Description="replace value"  

[Mouse.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Modalias="usb:v1532p004Fd0200dc00dsc00dp00ic03isc"
  Uniq="replace value"  
  PROP="replace value"  
  EV="replace value"  
  KEY="replace value"  
  MSC="replace value"  
  Device File="replace value"  
  Hardware Class="replace value"  
  physical id="replace value"  
  Model="replace value"  
  Interface="replace value"  
  Bus Info="replace value"  
  Speed="replace value"  
  Maximum Current="replace value"  
  Capabilities="replace value"  
  Revision="replace value"  
  Description="replace value"  

[Printer.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  copies="replace value"  
  job-cancel-after="replace value"  
  job-hold-until="replace value"  
  job-priority="replace value"  
  marker-change-time="replace value"  
  number-up="replace value"  
  orientation-requested="replace value"  
  print-color-mode="replace value"  
  printer-is-accepting-jobs="replace value"  
  printer-is-shared="replace value"  
  printer-is-temporary="replace value"  
  printer-state-change-time="replace value"  
  printer-state-reasons="replace value"  
  printer-type="replace value"  
  printer-uri-supported="replace value"  
  sides="replace value"  
  Model="replace value"  
  Serial Number="replace value"  
  Shared="replace value"  
  URI="replace value"  
  Status="replace value"  
  Interface Type="replace value"  
  printer-make-and-model="replace value"  

[Camera.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Model="replace value"  
  Bus Info="replace value"  
  Speed="replace value"  
  Maximum Power="replace value"  
  Capabilities="replace value"  
  Serial Number="replace value" 

 

[CDROM.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Serial ID="replace value"  
  Driver Modules="replace value"  
  Device File="replace value"  
  Device Files="replace value"  
  device Number="replace value"  
  Config Status="replace value"  
  Application="replace value"  
  physical id="replace value"  
  status="replace value"  
  logical name="replace value"  
  ansi  Version="replace value"  
  Model="replace value"  
  Bus Info="replace value"  
  Capabilities="replace value"  
  Maximum Power="replace value"  
  Speed="replace value"  

[OtherDevices.VendorLabel]
  Vendor="replace value"  
  Name="replace value"  
  Device File="replace value"  
  Hardware Class="replace value"  
  Model="replace value"  
  Bus Info="replace value"  
  Capabilities="replace value"  
  Maximum Power="replace value"  
  Speed="replace value"  
  Serial Number="replace value"  


#1. 书写规则定义与说明：
#1-1. #号开关的为注释，文件格式按toml中表和键值对的格式书写，一个表头和下面的键值对代表一个设备信息；若信息不作替换处理，可不写上键值对。
#1-2.表头命名格式为[hardClassName.VendorLabel] 其中的hardClassName已确定如上关键，不可更改，“.VendorLabel”可由厂商自行定义，或可没有。
#1-3.键值对不可换行，键名取值已在代码中定义如上；相同键名，其值将替换同设备中对应的信息； replace value 需由厂商自行定义；若包括有"_NOUSE"，该条信息将不被显示。
#1-4.主板(Motherboard)相关信息显示中的Name键值对值不更改，且相同Name表数量不能超过一个，Motherboard表下共5个已定义名字设备。
#1-5.Computer表数量不能超过一个。

#2 同设备匹配方法及处理方法如下
#2-1."Modalias"与原显示设备中的Module Alias值相同会被当同一设备作信息替代； 包括有"_NOUSE"则该个设备所有信息将不会被显示。
#2-2."Vendor_ID, Product_ID"与原显示设备中的"Physical ID"中VID和PID值相同会被当同一设备作信息替代； 包括有"_NOUSE"则该个设备所有信息将不会被显示。
#2-3."Vendor, Name"包括有"_NOUSE"与原显示设备中的"Vendor，Name"值相同会被当同一设备作信息替代； 包括有"_NOUSE"则该个设备所有信息将不会被显示。


#3 文件名相关说明如下：
#3-1.文件相关的描述，主要是方便管控升级, 格式为《oeminfo_manufacturer_productname_version_serialnumber.toml》
#3-2.其中的关键字：Manufacturer、Product Name、Version、Serial Number，为命令sudo dmidecode -t 1 取其对应的值。
#3-3.文件名按照Linux文件命名规则，且字母全转化为小写，并去掉不可显示特殊字符和空格及"-/'~!@#$%^&*(){}:;,.\"\\|~`"字符。
#3-4.当前PC的文件名可从~/.cache/deepin/deepin-devicemanager/deepin-devicemanager.log中查询出，搜寻关键字为：“Toml File name  is: /etc/deepin/hardware/"。

#4.设备管理器启动时，解析出该机型对应的oeminfo_xx.toml文件名，然后到目录 /etc/deepin/hardware/ 中查找该文件，并打开读取相应信息，按上述规则作处理并显示。


